exports.names = [
  "Abdirasak Ahmed",
  "Abdullah Ahmed",
  "Adam Sackfield",
  // "Akin Fagbohun",
  "Alasdair Mcwilliam",
  // "Alfred Betts",
  "Ali Combes",
  "Alistair Sinclair-Smith",
  "Andrew Torr",
  "Cam Lindsay",
  "Chris Strafford",
  "Christos Nicolou",
  "Dane Whitfield",
  // "Diana Vozanu",
  "Eunjeong Sim",
  "Feras Mahmoud",
  // "Gareth Dawson",
  "Gareth Everson",
  "Gareth Williams",
  "Hazem Fahad",
  "Isaak Garside",
  "James Barlow",
  "James Harvey",
  "Jiyoung Kim",
  "John Murphy",
  // "Joseph Hawkins",
  "Jurijs Sorokins",
  "Kamahl Haider",
  "Kavi Parmar",
  "Mark Wills",
  "Michal Lewczuk",
  // "Mohamad Badwe AlNajjar",
  "Mohamed Mohamed",
  "Nathaniel Kane ",
  "Nicholas Wootton",
  "Nicola Lockwood",
  "Owen Corrigan",
  "Richard Parle",
  "Ryan Nuttall",
  "Salem Abushima",
  "Sam Richmond",
  "Shakeel Ahmed",
  // "Shaun Clarke",
  "Sheroze Mohammed",
  "Simon rosellys",
  "Suzanne Clifton",
  "Temi Alao",
  "Tim Tucker",
  "Tom Johnson",
  "Tomek Pikniczka",
  "Waleed Al-Rwaishan",
  "William Mason",
  // "Yousef Abobaker",
  "Zack Hamnet",
  "Abdinasir Mohamed",
  "HEATHER",
  "Rose",
  "karla",
  "jade",
  "paul",
  "jatinder",
];
